// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Swagger Hello world

    Schemes:
      http
    Host: localhost:8080
    BasePath: /
    Version: 1.0.0
    License: MIT

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
