swagger: "2.0"

info:
  version: 1.0.0
  title: Swagger Hello world
  license:
    name: MIT

host: localhost:8080

schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

definitions:
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
