// Code generated by go-swagger; DO NOT EDIT.

package hello

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/julianpitt/go-swagger-test/restapi/models"
)

// SayHelloOKCode is the HTTP code returned for type SayHelloOK
const SayHelloOKCode int = 200

/*SayHelloOK value from hello function

swagger:response sayHelloOK
*/
type SayHelloOK struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewSayHelloOK creates SayHelloOK with default headers values
func NewSayHelloOK() *SayHelloOK {

	return &SayHelloOK{}
}

// WithPayload adds the payload to the say hello o k response
func (o *SayHelloOK) WithPayload(payload *models.Message) *SayHelloOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the say hello o k response
func (o *SayHelloOK) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SayHelloOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SayHelloInternalServerErrorCode is the HTTP code returned for type SayHelloInternalServerError
const SayHelloInternalServerErrorCode int = 500

/*SayHelloInternalServerError Internal Server Error

swagger:response sayHelloInternalServerError
*/
type SayHelloInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSayHelloInternalServerError creates SayHelloInternalServerError with default headers values
func NewSayHelloInternalServerError() *SayHelloInternalServerError {

	return &SayHelloInternalServerError{}
}

// WithPayload adds the payload to the say hello internal server error response
func (o *SayHelloInternalServerError) WithPayload(payload *models.Error) *SayHelloInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the say hello internal server error response
func (o *SayHelloInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SayHelloInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
